void readPrimitives(prim_vec_t & ); 
void writePrimitives(prim_vec_t );
void readPositions(pos_vec_t & , string );
void writePositions(pos_vec_t );
void writePositionsToFile(pos_vec_t , string );
void readDimension(dimension_t &);
void writeDimension(dimension_t);
void writeDimensionToFile(dimension_t );
void getPrimitiveCost(prim_vec_t , prim_cost_t & );
void writePrimitiveCost(prim_cost_t & );
